config/routes.rb
Rails.application.routes.draw do

  resources :works, :only => [:index, :destroy]

  root 'works#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :inventories
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :category
  has_one :work, :dependent => :delete

  after_destroy :create_log

  scope :size_equal, -> (s) { where(:size => s) }

  validates :size, numericality: { greater_than: 0 }

  def create_log
    Log.create("The item with serial #{self.serial} has been deleted")
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :works, :dependent => :delete_all

  validates :name, presence: true
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  belongs_to :inventory

  scope :last_5, -> { last(5) }
  scope :no_item, -> { where(:inventory => nil) }

  validate :validates_user

  def validates_user
    if self.user_id.nil?
      errors.add(:user_id, 'is required')
    else
      if User.where(:id => self.user_id).size == 0
        errors.add(:user_id, 'must exist')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
      @works = Work.all
  end

  def destroy
    @work = Work.find(params[:id])
    @work.destroy
    redirect_to works_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba2RobertoLimon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/works/index.html.erb
<h1>Works list</h1>

<table>
  <thead>
    <th>Name</th>
    <th>Category</th>
    <th>User</th>
    <th></th>
  </thead>
  <tbody>
    <% @works.each do |w| %>
      <tr>
        <td><%= w.inventory.serial %></td>
        <td><%= w.inventory.category.name %></td>
        <td><%= w.user.name %></td>
        <td>
          <%= link_to "Delete", work_path(w), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>